// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.960
package views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func ObraFormUpdateContent() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<form id=\"formulario\" method=\"POST\" action=\"/update\"><label for=\"id\">ID:</label> <input type=\"text\" id=\"id\" name=\"id\" required> <label for=\"titulo\">Titulo:</label> <input type=\"text\" id=\"titulo\" name=\"titulo\"> <label for=\"artista\">Artista:</label> <input type=\"text\" id=\"artista\" name=\"artista\"> <label for=\"descripcion\">Descripcion:</label> <input type=\"text\" id=\"descripcion\" name=\"descripcion\"> <label for=\"precio\">Precio:</label> <input type=\"text\" id=\"precio\" name=\"precio\"> <label for=\"vendida\" class=\"checkbox-label\">Vendida: <input type=\"checkbox\" id=\"vendida\" name=\"vendida\"></label> <button type=\"submit\">Enviar</button></form>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
